name: Python tests
on: 
  push:
    branches: ["main"]
jobs:
  run_ruff:
    name: Run ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ruff
        run: curl -LsSf https://astral.sh/ruff/install.sh | sh

      - name: Run ruff
        run: ruff check *.py
